jobs/urls.py
from django.views.generic import TemplateView

from . import views
from . import feeds
from django.urls import path

app_name = 'jobs'
urlpatterns = [
    path('', views.JobList.as_view(), name='job_list'),
    path('feed/rss/', feeds.JobFeed(), name='job_rss'),
    path('create/', views.JobCreate.as_view(), name='job_create'),
    path('create-review-comment/', views.JobReviewCommentCreate.as_view(), name='job_review_comment_create'),
    path('mine/', views.JobListMine.as_view(), name='job_list_mine'),
    path('review/', views.JobReview.as_view(), name='job_review'),
    path('moderate/', views.JobModerateList.as_view(), name='job_moderate'),
    path('thanks/', TemplateView.as_view(template_name="jobs/job_thanks.html"), name='job_thanks'),
    path('location/telecommute/', views.JobTelecommute.as_view(), name='job_telecommute'),
    path('location/<slug:slug>/', views.JobListLocation.as_view(), name='job_list_location'),
    path('type/<slug:slug>/', views.JobListType.as_view(), name='job_list_type'),
    path('category/<slug:slug>/', views.JobListCategory.as_view(), name='job_list_category'),
    path('locations/', views.JobLocations.as_view(), name='job_locations'),
    path('types/', views.JobTypes.as_view(), name='job_types'),
    path('categories/', views.JobCategories.as_view(), name='job_categories'),
    path('<int:pk>/edit/', views.JobEdit.as_view(), name='job_edit'),
    path('<int:pk>/preview/', views.JobPreview.as_view(), name='job_preview'),
    path('<int:pk>/remove/', views.JobRemove.as_view(), name='job_remove'),
    path('<int:pk>/', views.JobDetail.as_view(), name='job_detail'),
]

sponsors/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('application/new/', views.NewSponsorshipApplicationView.as_view(),
        name="new_sponsorship_application",
    ),
    path('application/', views.SelectSponsorshipApplicationBenefitsView.as_view(),
        name="select_sponsorship_application_benefits",
    ),
]

sponsors/models/assets.py
"""
This module holds models to store generic assets
from Sponsors or Sponsorships
"""
import uuid
from enum import Enum
from pathlib import Path

from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db.models.fields.files import ImageFieldFile, FileField
from polymorphic.managers import PolymorphicManager
from polymorphic.models import PolymorphicModel

from sponsors.models.managers import GenericAssetQuerySet


def generic_asset_path(instance, filename):
    """
    Uses internal name + content type + obj id to avoid name collisions
    """
    directory = "sponsors-app-assets"
    ext = "".join(Path(filename).suffixes)
    name = f"{instance.uuid}"
    return f"{directory}/{name}{ext}"


class GenericAsset(PolymorphicModel):
    """
    Base class used to add required assets to Sponsor or Sponsorship objects
    """
    objects = GenericAssetQuerySet.as_manager()
    non_polymorphic = models.Manager()

    # UUID can't be the object ID because Polymorphic expects default django integer ID
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    # The next 3 fields are required by Django to enable and set up generic relations
    # pointing the asset to a Sponsor or Sponsorship object
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    # must match with internal_name from benefits configuration which describe assets
    internal_name = models.CharField(
        max_length=128,
        verbose_name="Internal Name",
        db_index=True,
    )

    class Meta:
        verbose_name = "Asset"
        verbose_name_plural = "Assets"
        unique_together = ["content_type", "object_id", "internal_name"]
        base_manager_name = 'non_polymorphic'

    @property
    def value(self):
        return None

    @property
    def is_file(self):
        return isinstance(self.value, FileField) or isinstance(self.value, ImageFieldFile)

    @property
    def from_sponsorship(self):
        return self.content_type.name == "sponsorship"

    @property
    def from_sponsor(self):
        return self.content_type.name == "sponsor"

    @property
    def has_value(self):
        if self.is_file:
            return self.value and getattr(self.value, "url", None)
        else:
            return bool(self.value)

    @classmethod
    def all_asset_types(cls):
        return cls.__subclasses__()


class ImgAsset(GenericAsset):
    image = models.ImageField(
        upload_to=generic_asset_path,
        blank=False,
        null=True,
    )

    def __str__(self):
        return f"Image asset: {self.internal_name}"

    class Meta:
        verbose_name = "Image Asset"
        verbose_name_plural = "Image Assets"

    @property
    def value(self):
        return self.image

    @value.setter
    def value(self, value):
        self.image = value


class TextAsset(GenericAsset):
    text = models.TextField(default="")

    def __str__(self):
        return f"Text asset: {self.internal_name}"

    class Meta:
        verbose_name = "Text Asset"
        verbose_name_plural = "Text Assets"

    @property
    def value(self):
        return self.text

    @value.setter
    def value(self, value):
        self.text = value


class FileAsset(GenericAsset):
    file = models.FileField(
        upload_to=generic_asset_path,
        blank=False,
        null=True,
    )

    def __str__(self):
        return f"File asset: {self.internal_name}"

    class Meta:
        verbose_name = "File Asset"
        verbose_name_plural = "File Assets"

    @property
    def value(self):
        return self.file

    @value.setter
    def value(self, value):
        self.file = value


class Response(Enum):
    YES = "Yes"
    NO = "No"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)


class ResponseAsset(GenericAsset):
    response = models.CharField(
        max_length=32, choices=Response.choices(), blank=False, null=True
    )

    def __str__(self):
        return f"Response Asset: {self.internal_name}"

    class Meta:
        verbose_name = "Response Asset"
        verbose_name_plural = "Response Assets"

    @property
    def value(self):
        return self.response

    @value.setter
    def value(self, value):
        self.response = value

sponsors/models/enums.py
from enum import Enum


class LogoPlacementChoices(Enum):
    SIDEBAR = "sidebar"
    SPONSORS_PAGE = "sponsors"
    JOBS = "jobs"
    BLOG = "blogpost"
    FOOTER = "footer"
    DOCS = "docs"
    DOWNLOAD_PAGE = "download"
    DEV_GUIDE = "devguide"


class PublisherChoices(Enum):
    FOUNDATION = "psf"
    PYCON = "pycon"
    PYPI = "pypi"
    CORE_DEV = "core"


class AssetsRelatedTo(Enum):
    SPONSOR = "sponsor"
    SPONSORSHIP = "sponsorship"

sponsors/models/sponsors.py
"""
This module holds models related to the Sponsor entity.
"""
from allauth.account.models import EmailAddress
from django.conf import settings
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.template.defaultfilters import slugify
from django.urls import reverse
from django_countries.fields import CountryField
from ordered_model.models import OrderedModel
from django.contrib.contenttypes.fields import GenericRelation

from cms.models import ContentManageable
from sponsors.models.assets import GenericAsset
from sponsors.models.managers import SponsorContactQuerySet


class Sponsor(ContentManageable):
    """
    Group all of the sponsor information, logo and contacts
    """

    name = models.CharField(
        max_length=100,
        verbose_name="Name",
        help_text="Name of the sponsor, for public display.",
    )
    description = models.TextField(
        verbose_name="Description",
        help_text="Brief description of the sponsor for public display.",
    )
    landing_page_url = models.URLField(
        blank=True,
        null=True,
        verbose_name="Landing page URL",
        help_text="Landing page URL. This may be provided by the sponsor, however the linked page may not contain any "
                  "sales or marketing information.",
    )
    twitter_handle = models.CharField(
        max_length=32,  # Actual limit set by twitter is 15 characters, but that may change?
        blank=True,
        null=True,
        verbose_name="Twitter handle",
    )
    web_logo = models.ImageField(
        upload_to="sponsor_web_logos",
        verbose_name="Web logo",
        help_text="For display on our sponsor webpage. High resolution PNG or JPG, smallest dimension no less than "
                  "256px",
    )
    print_logo = models.FileField(
        upload_to="sponsor_print_logos",
        blank=True,
        null=True,
        verbose_name="Print logo",
        help_text="For printed materials, signage, and projection. SVG or EPS",
    )

    primary_phone = models.CharField("Primary Phone", max_length=32)
    mailing_address_line_1 = models.CharField(
        verbose_name="Mailing Address line 1", max_length=128, default=""
    )
    mailing_address_line_2 = models.CharField(
        verbose_name="Mailing Address line 2", max_length=128, blank=True, default=""
    )
    city = models.CharField(verbose_name="City", max_length=64, default="")
    state = models.CharField(
        verbose_name="State/Province/Region", max_length=64, blank=True, default=""
    )
    postal_code = models.CharField(
        verbose_name="Zip/Postal Code", max_length=64, default=""
    )
    country = CountryField(default="")
    assets = GenericRelation(GenericAsset)

    class Meta:
        verbose_name = "sponsor"
        verbose_name_plural = "sponsors"

    def verified_emails(self, initial_emails=None):
        emails = initial_emails if initial_emails is not None else []
        for contact in self.contacts.all():
            if EmailAddress.objects.filter(
                email__iexact=contact.email, verified=True
            ).exists():
                emails.append(contact.email)
        return list(set({e.casefold(): e for e in emails}.values()))

    def __str__(self):
        return f"{self.name}"

    @property
    def full_address(self):
        addr = self.mailing_address_line_1
        if self.mailing_address_line_2:
            addr += f" {self.mailing_address_line_2}"
        return f"{addr}, {self.city}, {self.state}, {self.country}"

    @property
    def primary_contact(self):
        try:
            return SponsorContact.objects.get_primary_contact(self)
        except SponsorContact.DoesNotExist:
            return None

    @property
    def slug(self):
        return slugify(self.name)

    @property
    def admin_url(self):
        return reverse("admin:sponsors_sponsor_change", args=[self.pk])


class SponsorContact(models.Model):
    """
    Sponsor contact information
    """
    PRIMARY_CONTACT = "primary"
    ADMINISTRATIVE_CONTACT = "administrative"
    ACCOUTING_CONTACT = "accounting"
    MANAGER_CONTACT = "manager"
    CONTACT_TYPES = [
        (PRIMARY_CONTACT, "Primary"),
        (ADMINISTRATIVE_CONTACT, "Administrative"),
        (ACCOUTING_CONTACT, "Accounting"),
        (MANAGER_CONTACT, "Manager"),
    ]

    objects = SponsorContactQuerySet.as_manager()

    sponsor = models.ForeignKey(
        "Sponsor", on_delete=models.CASCADE, related_name="contacts"
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE
    )  # Optionally related to a User! (This needs discussion)
    primary = models.BooleanField(
        default=False,
        help_text="The primary contact for a sponsorship will be responsible for managing deliverables we need to "
                  "fulfill benefits. Primary contacts will receive all email notifications regarding sponsorship. "
    )
    administrative = models.BooleanField(
        default=False,
        help_text="Administrative contacts will only be notified regarding contracts."
    )
    accounting = models.BooleanField(
        default=False,
        help_text="Accounting contacts will only be notified regarding invoices and payments."
    )
    manager = models.BooleanField(
        default=False,
        help_text="If this contact can manage sponsorship information on python.org",
    )
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=256)
    phone = models.CharField("Contact Phone", max_length=32)

    # Sketch of something we'll need to determine if a user is able to make _changes_ to sponsorship
    # benefits/logos/descriptons/etc.
    @property
    def can_manage(self):
        if self.user is not None and (self.primary or self.manager):
            return True

    @property
    def type(self):
        types=[]
        if self.primary:
            types.append('Primary')
        if self.administrative:
            types.append('Administrative')
        if self.manager:
            types.append('Manager')
        if self.accounting:
            types.append('Accounting')
        return ", ".join(types)

    def __str__(self):
        return f"Contact {self.name} from {self.sponsor}"


class SponsorBenefit(OrderedModel):
    """
    Link a benefit to a sponsorship application.
    Created after a new sponsorship
    """

    sponsorship = models.ForeignKey(
        'sponsors.Sponsorship', on_delete=models.CASCADE, related_name="benefits"
    )
    sponsorship_benefit = models.ForeignKey(
        'sponsors.SponsorshipBenefit',
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        help_text="Sponsorship Benefit this Sponsor Benefit came from",
    )
    program_name = models.CharField(
        max_length=1024,
        verbose_name="Program Name",
        help_text="For display in the contract and sponsor dashboard."
    )
    name = models.CharField(
        max_length=1024,
        verbose_name="Benefit Name",
        help_text="For display in the contract and sponsor dashboard.",
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name="Benefit Description",
        help_text="For display in the contract and sponsor dashboard.",
    )
    program = models.ForeignKey(
        'sponsors.SponsorshipProgram',
        null=True,
        blank=False,
        on_delete=models.SET_NULL,
        verbose_name="Sponsorship Program",
        help_text="Which sponsorship program the benefit is associated with.",
    )
    benefit_internal_value = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name="Benefit Internal Value",
        help_text="Benefit's internal value from when the Sponsorship gets created",
    )
    added_by_user = models.BooleanField(
        blank=True, default=False, verbose_name="Added by user?"
    )
    standalone = models.BooleanField(
        blank=True, default=False, verbose_name="Added as standalone benefit?"
    )

    def __str__(self):
        if self.program is not None:
            return f"{self.program} > {self.name}"
        return f"{self.program_name} > {self.name}"

    @property
    def features(self):
        return self.benefitfeature_set

    @classmethod
    def new_copy(cls, benefit, **kwargs):
        kwargs["added_by_user"] = kwargs.get("added_by_user") or benefit.standalone
        kwargs["standalone"] = benefit.standalone
        sponsor_benefit = cls.objects.create(
            sponsorship_benefit=benefit,
            program_name=benefit.program.name,
            name=benefit.name,
            description=benefit.description,
            program=benefit.program,
            benefit_internal_value=benefit.internal_value,
            **kwargs,
        )

        # generate benefit features from benefit features configurations
        for feature_config in benefit.features_config.all():
            feature_config.create_benefit_feature(sponsor_benefit)

        return sponsor_benefit

    @property
    def legal_clauses(self):
        if self.sponsorship_benefit is not None:
            return self.sponsorship_benefit.legal_clauses.all()
        return []

    @property
    def name_for_display(self):
        name = self.name
        for feature in self.features.all():
            name = feature.display_modifier(name)
        return name

    def reset_attributes(self, benefit):
        """
        This method resets all the sponsor benefit information
        fetching new data from the sponsorship benefit.
        """
        self.program_name = benefit.program.name
        self.name = benefit.name
        self.description = benefit.description
        self.program = benefit.program
        self.benefit_internal_value = benefit.internal_value
        self.standalone = benefit.standalone

templates/sponsors/new_sponsorship_application_form.html
{% extends "psf/full-width.html" %}
{% load boxes widget_tweaks %}
{% load humanize %}
{% load sponsors %}


{% block page_title %}Submit Sponsorship Information{% endblock %}

{% block content %}
  <article id="new_sponsorship_application_container" class="text">
    <h1>Submit Sponsorship Information</h1>

    <div id="sponsorship-info-container" class="user-feedback level-general">
      {% if sponsorship_package %}
      <p>
        You selected the <b>{{ sponsorship_package.name }}</b> package {% if sponsorship_price %}costing ${{ sponsorship_price|intcomma }} USD {% endif %}and the following benefits:
      </p>
      <ul>
        {% for benefit in sponsorship_benefits %}
          <li>{% benefit_name_for_display benefit sponsorship_package %}</li>
        {% endfor %}
      </ul>
      {% endif %}

      {% if added_benefits %}
      <p>Added benefits:</p>
      <ul>
        {% for benefit in added_benefits %}
          <li>{% benefit_name_for_display benefit sponsorship_package %}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <p><i>Please complete the form below.</i></p>
      <span class="remove"><label id="close-info-container">Close</label> | <a href="{% url 'select_sponsorship_application_benefits' %}">Back to select benefits</a></span>
    </div>

    {% if form.errors %}
    <span class="error-message">The form has one or more errors</span>
    {{ form.non_field_errors }}
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      {% if form.user_with_previous_sponsors %}
      <p id="sponsor-select-field" class="form_field">
        <label>{{ form.sponsor.label }} <span class="error-message">{% if form.sponsor.errors %}{{ form.sponsor.errors.as_text }}</span>{% endif %}</label>
        {% render_field form.sponsor %}
        <br/>
        <span class="helptext">Your user account is already associated with existing PSF Sponsors. Select an existing sponsor to submit this application on their behalf or <span id="new-application-link">create a new one</span></span>.
      </p>
      {% endif %}

      <div id="new-appication-fields" {% if form.user_with_previous_sponsors and not form.errors %}style="display: none"{% endif %}>

        <p class="form_field">
          <label>{{ form.name.label }} <span class="error-message">{% if form.name.errors %}{{ form.name.errors.as_text }}</span>{% endif %}</label>
          {% render_field form.name %}
          {% if form.name.help_text %}
          <br/>
          <span class="helptext">{{ form.name.help_text }}</span>
          {% endif %}
        </p>

        <p class="form_field">
          <label>{{ form.description.label }} <span class="error-message">{% if form.description.errors %}{{ form.description.errors.as_text }}</span>{% endif %}</label>
          {% render_field form.description %}
          {% if form.description.help_text %}
          <br/>
          <span class="helptext">{{ form.description.help_text }}</span>
          {% endif %}
        </p>

        <div class="inline_fields">
          <div>
            <p class="form_field">
              <label>{{ form.landing_page_url.label }} <span class="error-message">{% if form.landing_page_url.errors %}{{ form.landing_page_url.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.landing_page_url %}
              {% if form.landing_page_url.help_text %}
              <br/>
              <span class="helptext">{{ form.landing_page_url.help_text }}</span>
              {% endif %}
            </p>
          </div>

          <div>
            <p class="form_field">
              <label>{{ form.twitter_handle.label }} <span class="error-message">{% if form.twitter_handle.errors %}{{ form.twitter_handle.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.twitter_handle %}
              {% if form.twitter_handle.help_text %}
              <br/>
              <span class="helptext">{{ form.twitter_handle.help_text }}</span>
              {% endif %}
            </p>
          </div>
        </div>

        <p class="form_field">
          <label>{{ form.country.label }} <span class="error-message">{% if form.country.errors %}{{ form.country.errors.as_text }}</span>{% endif %}</label>
          {% render_field form.country %}
          {% if form.country.help_text %}
          <br/>
          <span class="helptext">{{ form.country.help_text }}</span>
          {% endif %}
        </p>

        <div class="inline_fields">
          <div>
            <p class="form_field">
              <label>{{ form.mailing_address_line_1.label }} <span class="error-message">{% if form.mailing_address_line_1.errors %}{{ form.mailing_address_line_1.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.mailing_address_line_1 %}
              {% if form.mailing_address_line_1.help_text %}
              <br/>
              <span class="helptext">{{ form.mailing_address_line_1.help_text }}</span>
              {% endif %}
            </p>
          </div>

          <div>
            <p class="form_field">
              <label>{{ form.mailing_address_line_2.label }} <span class="error-message">{% if form.mailing_address_line_2.errors %}{{ form.mailing_address_line_2.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.mailing_address_line_2 %}
              {% if form.mailing_address_line_2.help_text %}
              <br/>
              <span class="helptext">{{ form.mailing_address_line_2.help_text }}</span>
              {% endif %}
            </p>
          </div>
        </div>

        <div class="inline_fields">
          <div>
            <p class="form_field">
              <label>{{ form.city.label }} <span class="error-message">{% if form.city.errors %}{{ form.city.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.city %}
              {% if form.city.help_text %}
              <br/>
              <span class="helptext">{{ form.city.help_text }}</span>
              {% endif %}
            </p>
          </div>

          <div>
            <p class="form_field">
              <label>{{ form.state.label }} <span class="error-message">{% if form.state.errors %}{{ form.state.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.state %}
              {% if form.state.help_text %}
              <br/>
              <span class="helptext">{{ form.state.help_text }}</span>
              {% endif %}
            </p>
          </div>
        </div>


        <div class="inline_fields">
          <div>
            <p class="form_field">
              <label>{{ form.postal_code.label }} <span class="error-message">{% if form.postal_code.errors %}{{ form.postal_code.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.postal_code %}
              {% if form.postal_code.help_text %}
              <br/>
              <span class="helptext">{{ form.postal_code.help_text }}</span>
              {% endif %}
            </p>
          </div>

          <div>
            <p class="form_field">
              <label>{{ form.primary_phone.label }} <span class="error-message">{% if form.primary_phone.errors %}{{ form.primary_phone.errors.as_text }}</span>{% endif %}</label>
              {% render_field form.primary_phone %}
              {% if form.primary_phone.help_text %}
              <br/>
              <span class="helptext">{{ form.primary_phone.help_text }}</span>
              {% endif %}
            </p>
          </div>
        </div>

        <div class="inline_fields">
          <div>
          <p class="form_field">
          <label>{{ form.web_logo.label }} <span class="error-message">{% if form.web_logo.errors %}{{ form.web_logo.errors.as_text }}</span>{% endif %}</label>
            {% render_field form.web_logo %}
            {% if form.web_logo.help_text %}
            <br/>
            <span class="helptext">{{ form.web_logo.help_text }}</span>
            {% endif %}
          </p>
          </div>

          <div>
          <p class="form_field">
            <label>{{ form.print_logo.label }} <span class="error-message">{% if form.print_logo.errors %}{{ form.print_logo.errors.as_text }}</span>{% endif %}</label>
            {% render_field form.print_logo %}
            {% if form.print_logo.help_text %}
            <br/>
            <span class="helptext">{{ form.print_logo.help_text }}</span>
            {% endif %}
          </p>
          </div>
        </div>

        <h1>Contacts</h1>
          {{ form.contacts_formset.management_form }}
          <div class="sponsor-contacts-container">

            {% for form in form.contacts_formset %}
            <div class="contact-form form-row">
              <table>
                 {{ form }}
                 <tr class="remove {% if forloop.first %}remove-contact-row {% endif %}remove-form-row"><th><label>Remove contact</label></th></tr>
              </table>
            </div>
            {% endfor %}

          <button class="formset-btn add-form-row" type="button">Extra contact</button>
        </div>

      </div>

      <input id="submit-btn" type="submit" value="Apply">
    </form>
  </article>

{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script type='text/javascript'>
  // JS reference from https://medium.com/all-about-django/adding-forms-dynamically-to-a-django-formset-375f1090c2b0

  function updateElementIndex(el, prefix, ndx) {
      var id_regex = new RegExp('(' + prefix + '-\\d+)');
      var replacement = prefix + '-' + ndx;
      if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
      if (el.id) el.id = el.id.replace(id_regex, replacement);
      if (el.name) el.name = el.name.replace(id_regex, replacement);
  }
  function cloneMore(selector, prefix) {
      var newElement = $(selector).clone(true);
      var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
      newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
          var name = $(this).attr('name').replace('-' + (total-1) + '-', '-' + total + '-');
          var id = 'id_' + name;
          $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
      });
      newElement.find('label').each(function() {
          var forValue = $(this).attr('for');
          if (forValue) {
            forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
            $(this).attr({'for': forValue});
          }
      });
      newElement.find(".remove-contact-row").show();
      total++;
      $('#id_' + prefix + '-TOTAL_FORMS').val(total);
      $(selector).after(newElement);
      var conditionRow = $('.form-row:not(:last)');
      conditionRow.find('.btn.add-form-row')
      .removeClass('btn-success').addClass('btn-danger')
      .removeClass('add-form-row').addClass('remove-form-row')
      .html('<span class="glyphicon glyphicon-minus" aria-hidden="true"></span>');

      var maxForms = $('#id_' + prefix + '-MAX_NUM_FORMS').val();
      if (total >= maxForms) {
          $(".add-form-row").hide();
      }

      return false;
  }
  function deleteForm(prefix, btn) {
      var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
      if (total > 1){
          btn.closest('.form-row').remove();
          var forms = $('.form-row');
          $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
          for (var i=0, formCount=forms.length; i<formCount; i++) {
              $(forms.get(i)).find(':input').each(function() {
                  updateElementIndex(this, prefix, i);
              });
          }
          $(".add-form-row").show();
      }
      return false;
  }
  let formPrefix = "contact";
  $(document).on('click', '.add-form-row', function(e){
      e.preventDefault();
      cloneMore('.form-row:last', formPrefix);
      return false;
  });
  $(document).on('click', '.remove-form-row', function(e){
      e.preventDefault();
      deleteForm(formPrefix, $(this));
      return false;
  });
  $(document).on("change", "#id_sponsor", function(e){
      e.preventDefault();
      let sponsor = $(this).val();
      if (sponsor.length) {
          $("#new-appication-fields").hide();
          $('input[required=""]').removeAttr("required");
      }
      return false;
  });
  $(document).on("click", "#new-application-link", function(e){
      e.preventDefault();
      console.log('vai');
      $("#id_sponsor").val("");
      $("#new-appication-fields").show();
      return false;
  });
  $(document).on("click", "#close-info-container", function(e){
      e.preventDefault();
      $("#sponsorship-info-container").hide();
      return false;
  });
</script>
{% endblock %}

templates/sponsors/sponsor_list.html
{% extends "base.html" %}
{% load boxes %}

{% block page_title %}Our Sponsors | {{ SITE_INFO.site_name }}{% endblock %}

{% block body_attributes %}class="psf users default-page"{% endblock %}


{% block main_navigation %}
{% load sitetree %}
{% sitetree_menu from "main" include "psf-meta" template "sitetree/submenu.html" %}
{% endblock %}

{% block main-nav_attributes %}psf-navigation{% endblock %}


{% block content_attributes %}with-right-sidebar{% endblock %}

{% block content %}

    <article class="text">
    
        <h1>PSF Sponsor Members</h1>
        <ul class="list-row-container menu">
        {% for sponsor in sponsors %}
            <li><a href="{{ sponsor.company.url }}">{{ sponsor.company.name }}</a></li>
        {% endfor %}
        </ul>
   
    </article>

{% endblock content %}


{% block right_sidebar %}
    <aside class="right-sidebar" role="secondary">
        
        <div class="sidebar-widget psf-sidebar-widget1">
            {% box 'psf-widget1' %}
            
        </div>

        <div class="sidebar-widget psf-sidebar-widget2">
            {% box 'psf-widget2' %}
            
        </div>

        <div class="sidebar-widget psf-sidebar-widget3">
            {% box 'psf-widget3' %}
            
        </div>

        <div class="sidebar-widget psf-sidebar-widget4 last">
            {% box 'psf-widget4' %}
            
        </div>
        
    </aside>
{% endblock right_sidebar %}