jobs/urls.py
from django.views.generic import TemplateView

from . import views
from . import feeds
from django.urls import path

app_name = 'jobs'
urlpatterns = [
    path('', views.JobList.as_view(), name='job_list'),
    path('feed/rss/', feeds.JobFeed(), name='job_rss'),
    path('create/', views.JobCreate.as_view(), name='job_create'),
    path('create-review-comment/', views.JobReviewCommentCreate.as_view(), name='job_review_comment_create'),
    path('mine/', views.JobListMine.as_view(), name='job_list_mine'),
    path('review/', views.JobReview.as_view(), name='job_review'),
    path('moderate/', views.JobModerateList.as_view(), name='job_moderate'),
    path('thanks/', TemplateView.as_view(template_name="jobs/job_thanks.html"), name='job_thanks'),
    path('location/telecommute/', views.JobTelecommute.as_view(), name='job_telecommute'),
    path('location/<slug:slug>/', views.JobListLocation.as_view(), name='job_list_location'),
    path('type/<slug:slug>/', views.JobListType.as_view(), name='job_list_type'),
    path('category/<slug:slug>/', views.JobListCategory.as_view(), name='job_list_category'),
    path('locations/', views.JobLocations.as_view(), name='job_locations'),
    path('types/', views.JobTypes.as_view(), name='job_types'),
    path('categories/', views.JobCategories.as_view(), name='job_categories'),
    path('<int:pk>/edit/', views.JobEdit.as_view(), name='job_edit'),
    path('<int:pk>/preview/', views.JobPreview.as_view(), name='job_preview'),
    path('<int:pk>/remove/', views.JobRemove.as_view(), name='job_remove'),
    path('<int:pk>/', views.JobDetail.as_view(), name='job_detail'),
]

jobs/forms.py
from django import forms
from django.forms.widgets import CheckboxSelectMultiple, HiddenInput

from markupfield.widgets import MarkupTextarea

from .models import Job, JobReviewComment
from cms.forms import ContentManageableModelForm


class JobForm(ContentManageableModelForm):
    required_css_class = 'required'

    class Meta:
        model = Job
        fields = (
            'job_title',
            'company_name',
            'category',
            'job_types',
            'other_job_type',
            'city',
            'region',
            'country',
            'description',
            'requirements',
            'company_description',
            'contact',
            'email',
            'url',
            'telecommuting',
            'agencies',
        )
        widgets = {
            'job_types': CheckboxSelectMultiple(),
        }
        help_texts = {
            'email': (
                "<b>This email address will be publicly displayed for "
                "applicants to contact if they are interested in the "
                "posting.</b>"
            ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['job_types'].help_text = None

    def save(self, commit=True):
        obj = super().save()
        obj.job_types.clear()
        for t in self.cleaned_data['job_types']:
            obj.job_types.add(t)
        return obj


class JobReviewCommentForm(ContentManageableModelForm):
    # We set 'required' to False because we can also set Job's status.
    # See JobReviewCommentCreate.form_valid() for details.
    comment = forms.CharField(required=False, widget=MarkupTextarea())

    class Meta:
        model = JobReviewComment
        fields = ['job', 'comment']
        widgets = {
            'job': HiddenInput(),
        }

    def save(self, commit=True):
        # Don't try to add a new comment if the 'comment' field is empty.
        if self.cleaned_data['comment']:
            return super().save(commit=commit)

jobs/views.py
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, View

from pydotorg.mixins import GroupRequiredMixin, LoginRequiredMixin

from .forms import JobForm, JobReviewCommentForm
from .models import Job, JobType, JobCategory, JobReviewComment


class JobListMenu:
    def job_list_view(self):
        return True


class JobTypeMenu:
    def job_type_view(self):
        return True


class JobCategoryMenu:
    def job_category_view(self):
        return True


class JobLocationMenu:
    def job_location_view(self):
        return True


class JobBoardAdminRequiredMixin(GroupRequiredMixin):
    group_required = "Job Board Admin"
    raise_exception = True

    def check_membership(self, group):
        # Add is_staff check to stay compatible with current staff members.
        # is_superuser check is already in base class.
        if self.request.user.is_staff:
            return True
        return super().check_membership(group)


class JobMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        active_locations = Job.objects.visible().distinct(
            'location_slug'
        ).order_by(
            'location_slug',
        )

        context.update({
            'jobs_count': Job.objects.visible().count(),
            'active_types': JobType.objects.with_active_jobs(),
            'active_categories': JobCategory.objects.with_active_jobs(),
            'active_locations': active_locations,
            'jobs_board_admin': self.has_jobs_board_admin_access(),
        })

        return context

    def has_jobs_board_admin_access(self):
        # Add is_staff and is_superuser checks to stay compatible
        # with current staff members.
        if self.request.user.is_staff or self.request.user.is_superuser:
            return True
        user_groups = self.request.user.groups.values_list('name', flat=True)
        return JobBoardAdminRequiredMixin.group_required in user_groups


class JobList(JobListMenu, JobMixin, ListView):
    model = Job
    paginate_by = 25

    def get_queryset(self):
        return super().get_queryset().visible().select_related()


class JobListMine(LoginRequiredMixin, JobMixin, ListView):
    paginate_by = 25

    def get_queryset(self):
        return Job.objects.by(self.request.user).select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mine_listing'] = True
        return context


class JobListType(JobTypeMenu, JobMixin, ListView):
    paginate_by = 25
    template_name = 'jobs/job_type_list.html'

    def get_queryset(self):
        self.current_type = get_object_or_404(JobType,
                                              slug=self.kwargs['slug'])
        return Job.objects.visible().select_related().filter(
            job_types__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_type'] = self.current_type
        return context


class JobListCategory(JobCategoryMenu, JobMixin, ListView):
    paginate_by = 25
    template_name = 'jobs/job_category_list.html'

    def get_queryset(self):
        self.current_category = get_object_or_404(JobCategory,
                                                  slug=self.kwargs['slug'])
        return Job.objects.visible().select_related().filter(
            category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_category'] = self.current_category
        return context


class JobListLocation(JobLocationMenu, JobMixin, ListView):
    paginate_by = 25
    template_name = 'jobs/job_location_list.html'

    def get_queryset(self):
        return Job.objects.visible().select_related().filter(
            location_slug=self.kwargs['slug'])


class JobTypes(JobTypeMenu, JobMixin, ListView):
    """ View to simply list JobType instances that have current jobs """
    template_name = "jobs/job_types.html"
    queryset = JobType.objects.with_active_jobs().order_by('name')
    context_object_name = 'types'


class JobCategories(JobCategoryMenu, JobMixin, ListView):
    """ View to simply list JobCategory instances that have current jobs """
    template_name = "jobs/job_categories.html"
    queryset = JobCategory.objects.with_active_jobs().order_by('name')
    context_object_name = 'categories'


class JobLocations(JobLocationMenu, JobMixin, TemplateView):
    """ View to simply list distinct Countries that have current jobs """
    template_name = "jobs/job_locations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['jobs'] = Job.objects.visible().distinct(
            'country', 'city'
        ).order_by(
            'country', 'city'
        )

        return context


class JobTelecommute(JobLocationMenu, JobList):
    """ Specific view for telecommute jobs """
    template_name = 'jobs/job_telecommute_list.html'

    def get_queryset(self):
        return super().get_queryset().visible().select_related().filter(
            telecommuting=True
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['jobs_count'] = len(self.object_list)
        context['jobs'] = self.object_list
        return context


class JobReview(LoginRequiredMixin, JobBoardAdminRequiredMixin, JobMixin, ListView):
    template_name = 'jobs/job_review.html'
    paginate_by = 20
    redirect_url = 'jobs:job_review'

    def get_queryset(self):
        return Job.objects.review()

    def post(self, request):
        try:
            job = Job.objects.get(id=request.POST['job_id'])
            action = request.POST['action']
        except (KeyError, Job.DoesNotExist):
            return redirect('jobs:job_review')

        if action == 'approve':
            job.approve(request.user)
            messages.add_message(self.request, messages.SUCCESS, "'%s' approved." % job)

        elif action == 'reject':
            job.reject(request.user)
            messages.add_message(self.request, messages.SUCCESS, "'%s' rejected." % job)

        elif action == 'remove':
            job.status = Job.STATUS_REMOVED
            job.save()
            messages.add_message(self.request, messages.SUCCESS, "'%s' removed." % job)

        elif action == 'archive':
            job.status = Job.STATUS_ARCHIVED
            job.save()
            messages.add_message(self.request, messages.SUCCESS, "'%s' archived." % job)
        else:
            raise Http404

        return redirect(self.redirect_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mode'] = 'review'
        return context


class JobRemove(LoginRequiredMixin, View):

    def get(self, request, pk):
        try:
            job = Job.objects.get(id=pk, creator=request.user)
        except Job.DoesNotExist:
            return redirect('jobs:job_list_mine')
        job.status = Job.STATUS_REMOVED
        job.save()
        messages.add_message(request, messages.SUCCESS, "'%s' removed." % job)
        return redirect('jobs:job_list_mine')


class JobModerateList(JobReview):
    redirect_url = 'jobs:job_moderate'

    def get_queryset(self):
        queryset = Job.objects.moderate()
        q = self.request.GET.get('q')
        if q is not None:
            return queryset.filter(job_title__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mode'] = 'moderate'
        return context


class JobDetail(JobMixin, DetailView):

    def get_queryset(self):
        queryset = Job.objects.select_related()
        if self.has_jobs_board_admin_access():
            return queryset
        if self.request.user.is_authenticated:
            # Combine visible jobs and user's non-visible jobs.
            # TODO: Add this to JobQuerySet and use where applicable.
            return queryset.visible() | queryset.by(self.request.user)
        return queryset.visible()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_jobs'] = self.object.category.jobs.select_related('category')[:5]
        context['user_can_edit'] = (
            self.object.creator == self.request.user or
            self.has_jobs_board_admin_access()
        ) and self.object.editable
        context['job_review_form'] = JobReviewCommentForm(initial={'job': self.object})
        return context


class JobPreview(LoginRequiredMixin, JobDetail, UpdateView):
    template_name = 'jobs/job_detail.html'
    form_class = JobForm

    def get_success_url(self):
        return reverse('jobs:job_thanks')

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        self.object = self.get_object()
        if self.request.POST.get('action') == 'review':
            self.object.review()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.get(request)

    def get_object(self, queryset=None):
        """ Show only approved jobs to the public, staff can see all jobs """
        job = super().get_object(queryset=queryset)
        # Only allow creator to preview and only while in draft status
        if job.creator == self.request.user and job.editable:
            return job

        if self.request.user.is_staff:
            return job

templates/jobs/base.html
{% extends "base.html" %}
{% load boxes %}
{% load sponsors %}

{% block body_attributes %}class="jobs"{% endblock %}

{% block main-nav_attributes %}jobs-navigation{% endblock %}

{% block header_content %}
<div class="jobs-intro">
    <h2 class="welcome-message">{% block header_message %}Get exploring!{% endblock %}</h2>
    <h1 class="call-to-action">{% block header_action %}{{ jobs_count }} jobs on the Python Job Board{% endblock %}</h1>
<!--
    <p class="excerpt">{% block header_excerpt %}<strong>Have a job to post?</strong> Please <a href="{% url 'jobs:job_create' %}">fill out this form</a>{% if not request.user.is_authenticated %}, or returning Job Board users may <a href="{% url 'account_login' %}?next={{ request.path }}">log in here</a> to update job postings and create new ones.{% else %}.{% endif %}{% endblock %}</p>
-->

</div>
{% endblock header_content %}

{% block main_navigation %}
<ul class="navigation menu" role="menubar" aria-label="Main Navigation">
    <li class="tier-1 element-1 {% if view.job_list_view %}current_item selected{% endif %}">
        <a href="{% url 'jobs:job_list' %}">Jobs</a>
    </li>
    <li class="tier-1 element-2 {% if view.job_type_view %}current_item selected{% endif %}" aria-haspopup="true">
        <a href="{% url 'jobs:job_types' %}">Types</a>
        <ul class="subnav menu" role="menu" aria-hidden="true">
            {% for t in active_types %}
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_list_type' slug=t.slug %}">{{ t.name }}</a></li>
            {% empty %}
            <li class="tier-2" role="treeitem">No Active Types</li>
            {% endfor %}
        </ul>
    </li>
    <li class="tier-1 element-3 {% if view.job_category_view %}current_item selected{% endif %}" aria-haspopup="true">
        <a href="{% url 'jobs:job_categories' %}">Categories</a>
        <ul class="subnav menu" role="menu" aria-hidden="true">
            {% for c in active_categories %}
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_list_category' slug=c.slug %}">{{ c.name }}</a></li>
            {% empty %}
            <li class="tier-2" role="treeitem">No Active Categories</li>
            {% endfor %}
        </ul>
    </li>
    <li class="tier-1 element-4 {% if view.job_location_view %}current_item selected{% endif %}">
        <a href="{% url 'jobs:job_locations' %}">Locations</a>
        <ul class="subnav menu" role="menu" aria-hidden="true">
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_telecommute' %}">Telecommute</a></li>
            {% for l in active_locations %}
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_list_location' slug=l.location_slug %}">
                {% if l.region and l.region != l.city %}
                    {{ l.city }}, {{ l.region }} &ndash; {{ l.country }}
                {% else %}
                    {{ l.city }} &ndash; {{ l.country }}
                {% endif %}
            </a></li>
            {% empty %}
            <li class="tier-2" role="treeitem">No Active Locations</li>
            {% endfor %}
        </ul>
    </li>
    <li class="tier-1 element-5{% if not jobs_board_admin %} last{% endif %}"><a href="{% url 'jobs:job_create' %}">Submit</a></li>
    {% if jobs_board_admin %}
    <li class="tier-1 element-6 last">
        <a href="{% url 'jobs:job_review' %}">Admin</a>
        <ul class="subnav menu" role="menu" aria-hidden="true">
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_review' %}">Review queue</a></li>
            <li class="tier-2" role="treeitem"><a href="{% url 'jobs:job_moderate' %}">Moderate approved posts</a></li>
        </ul>
    </li>
    {% endif %}
</ul>
{% endblock main_navigation %}

{% block right_sidebar %}
<aside class="right-sidebar">
    {% block right_sidebar_content %}

        {% block right_sidebar_header %}{% endblock %}

        {% include "jobs/submit_a_job-widget.html" %}
        {% include "jobs/featured_companies-widget.html" %}

        <div class="sidebar-widget">
            {% box 'jobs-subscribe' %}
        </div>

        <div class="sidebar-widget">
            {% list_sponsors 'jobs' %}
        </div>

        {% block right_sidebar_footer %}{% endblock %}

    {% endblock right_sidebar_content %}
</aside>
{% endblock right_sidebar %}

templates/jobs/header_content.html
<div class="jobs-intro">
    <h2 class="welcome-message">Get exploring! </h2>
    <h1 class="call-to-action">{{ jobs_count }} jobs from {{ companies_count }} companies on the Python Job Board</h1>
<!--
    <p class="excerpt"><strong>Have a job to post?</strong> Please <a href="{% url 'jobs:job_create' %}">fill out this form</a>{% if not request.user.is_authenticated %}, or returning Job Board users may <a href="{% url 'account_login' %}?next={{ request.path }}">log in here</a> to update job postings and create new ones.{% else %}.{% endif %} </p>
-->
</div>

templates/jobs/job_categories.html
{% extends "jobs/base.html" %}
{% load boxes %}

{% block page_title %}Our Job Categories | {{ SITE_INFO.site_name }}{% endblock %}
{% block content_attributes %}with-right-sidebar{% endblock %}

{% block header_message %}Job Categories{% endblock %}
{% block header_action %}{{ jobs_count }} Python jobs in {{ categories|length }} different categories{% endblock %}

{% block content %}
<div class="row">

    <ol class="list-recent-jobs list-row-container menu">
        {% for cat in categories %}
            <li><a href="{% url 'jobs:job_list_category' slug=cat.slug %}">{{ cat.name }}</a></li>
        {% endfor %}
    </ol>

</div>
{% endblock content %}

templates/jobs/job_category_list.html
{% extends "jobs/job_list.html" %}

{% block header_message %}{{ current_category.name }}{% endblock %}
{% block header_action %}{{ object_list|length }} Python job{{ object_list|length|pluralize }} in {{ current_category.name }}{% endblock %}

templates/jobs/job_detail.html
{% extends "jobs/base.html" %}
{% load boxes %}

{% block page_title %}{{ object.display_name }} | {{ SITE_INFO.site_name }}{% endblock %}

{% block body_attributes %}class="jobs default-page single-job"{% endblock %}

{% block content_attributes %}with-right-sidebar{% endblock %}

{% block og_title %}Job: {{ object.job_title }} at {{ object.company_name }}{% endblock %}
{% block og-descript %}{{ object.description|truncatechars:200 }}{% endblock %}

{% block content %}
{% load companies %}
<article class="text">

    {% if request.user.is_staff %}
    <p class="user-feedback level-notice">
        This job is in <strong>{{ object.status }}</strong> mode.
    </p>
    {% endif %}

	<h1 class="listing-company">
        <span class="listing-company-name">
	    <span class="company-name">
	      {{ object.job_title }}
              {% if object.is_new %}
	      <span class="listing-new">New</span>
              {% endif %}
	      <br/>
              {{ object.company_name }}
	    </span>
            {% if user_can_edit %}
	     <br/><a href="{% url 'jobs:job_edit' pk=object.pk %}">Edit your listing</a>
	    {% endif %}
        </span>
        <span class="listing-location"><a href="{% url 'jobs:job_list_location' slug=object.location_slug %}" title="More jobs in {{ object.display_location }}">{{object.display_location}}</a></span>
    </h1>

    <!-- User input html/markup/rst/whatever -->
    <div class="job-description">

        <h2>Job Title {% if object.status != 'approved' %}<small>({{ object.status }})</small>{% endif %}</h2>

        {{ object.job_title }}

        <h2>Job Description</h2>

        {{ object.description }}

        <h2>Restrictions</h2>
        <ul>
            {% if object.telecommuting %}
            <li><strong>Telecommuting is OK</strong></li>
            {% else %}
            <li><strong>No telecommuting</strong></li>
            {% endif %}

            {% if object.agencies %}
            <li><strong>Agencies are OK</strong></li>
            {% else %}
            <li><strong>No Agencies Please</strong></li>
            {% endif %}
        </ul>

        {% if object.requirements %}
        <h2>Requirements</h2>
        {{ object.requirements }}
        {% endif %}

        {% if object.display_description %}
        <h2>About the Company</h2>
        {{ object.display_description }}
        {% endif %}

        <h2>Contact Info</h2>
        <ul>
            {% if object.contact %}
            <li><strong>Contact</strong>: {{ object.contact }}</li>
            {% endif %}

            <li><strong>E-mail contact</strong>: <a class="reference external" href="mailto:{{ object.email|urlencode }}">{{ object.email|render_email }}</a></li>

            {% if object.url %}
            <li><strong>Web</strong>: <a class="reference external" href="{{ object.url }}">{{ object.url }}</a></li>
            {% endif %}
        </ul>

        {% if under_preview %}
            <form action="{% url "jobs:job_preview" pk=object.pk %}" method="post">
                {% csrf_token %}
                <a class="review_button button" href="{% url 'jobs:job_edit' pk=object.pk %}">Edit</a>
                <button name="action" value="review">Submit for Approval</button>
            </form>
        {% endif %}

        {% if not under_preview %}
        {% if jobs_board_admin or user_can_edit %}
            <hr>
            <h1>Comments are only viewable between the submitter and job reviewers.</h1>
            <h2>Job Review Discussion</h2>
            <dl id="comments">
            {% for comment in object.review_comments.all %}
                <dt>
                    <strong>{{ comment.created }} - {{ comment.creator.get_full_name|default:comment.creator.get_username }}</strong>
                </dt>
                <dd>
                    {{ comment.comment.rendered|safe }}
                </dd>
            {% endfor %}
            </dl>
            <form class="wide-form jobs-form" action="{% url 'jobs:job_review_comment_create' %}" method="post">
                {% csrf_token %}
                {{ job_review_form.as_p }}
                {% if user_can_edit and not jobs_board_admin %}
                <div>
                    <button type="submit" name="Submit">Submit</button>
                </div>
                {% elif jobs_board_admin %}
                <p>
                    <label for="canned_response">Insert canned response:</label>
                    <select id="canned_response">
                        <option value="empty">---</option>
                        <option value="not_python">No or not enough emphasis on Python</option>
                        <option value="formatting">Formatting broken</option>
                        <option value="duplicate">Duplicate posting</option>
                        <option value="voluntary">Voluntary, non paid job</option>
                    </select>
                </p>
                <div>
                    <a class="review_button button" href="{% url 'jobs:job_edit' pk=object.pk %}?next={{request.get_full_path}}">Edit</a>
                    <button type="submit" name="Submit">Comment</button>
                    {% if object.status != 'approved' %}
                    <button class="review_button" name="action" value="approve">Approve</button>
                    {% endif %}
                    {% if object.status != 'rejected' %}
                    <button class="review_button" name="action" value="reject">Reject</button>
                    {% endif %}
                </div>
                {% endif %}
            </form>
            <hr>
        {% endif %}
        {% endif %}


    </div><!-- end .job-post-content -->


    <div class="job-post-meta">
        <p class="job-meta">
            <!-- Company URL -->
            {% if object.company %}
            <span class="company-link"><a href="{{ object.company.url }}">{{ object.company.url }}</a></span>
            {% endif %}

            <!-- Date posted -->
            <span class="listing-posted">Posted <time datetime="{{ object.created|date:"c" }}">{{ object.created|date:"d F Y" }}</time></span>
        </p>

        <p class="job-tags">
            <!-- Job Types -->
            <span class="listing-job-type">{% for type in object.job_types.all %}<a href="{% url 'jobs:job_list_type' slug=type.slug %}" title="More {{ type.name }} jobs">{{ type.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</span>

            <!-- Company Category (Job Category) -->
            <span class="listing-company-category"><a href="{% url 'jobs:job_list_category' slug=object.category.slug %}" title="More jobs in {{ object.category.name }}">{{ object.category.name }}</a></span>
        </p>

        {% if request.user == object.creator and object.status == 'approved' %}
        <div class="listing-actions">
            <a class="button delete"
               href="{% url 'jobs:job_remove' pk=object.pk %}"
               onclick="return confirm('Are you sure? You can\'t undo this action.');">Remove</a>
        </div>
        {% endif %}
    </div>


</article>


<!-- Next or Previous Jobs by date posted -->
<p class="previous-next">
    {% with object.get_previous_listing as previous %}
        {% if previous %}
        <a class="prev-button" href="{{ previous.get_absolute_url }}">
            <span class="prev-button-text"><span class="icon-arrow-left"><span>&larr;</span></span> Previous</span>
            <span class="prevnext-description">
                <span class="company-name">{{ previous.display_name }}</span> in <span class="company-location">{{ previous.display_location }}</span>
            </span>
        </a>
        {% else %}
        <a class="prev-button disabled">
            <span class="prev-button-text"><span class="icon-arrow-left"><span>&larr;</span></span> Previous</span>
        </a>
        {% endif %}
    {% endwith %}

    {% with object.get_next_listing as next %}
        {% if next %}
        <a class="next-button" href="{{ next.get_absolute_url }}">
            <span class="next-button-text">Next <span class="icon-arrow-right"><span>&rarr;</span></span></span>
            <span class="prevnext-description">
                <span class="company-name">{{ next.display_name }}</span> in <span class="company-location">{{ next.display_location }}</span>
            </span>
        </a>
        {% else %}
        <a class="next-button disabled">
            <span class="next-button-text">Next <span class="icon-arrow-right"><span>&rarr;</span></span></span>
        </a>
        {% endif %}
    {% endwith %}
</p>
{% endblock content %}


{% block right_sidebar_header %}
    <div class="sidebar-widget">
        {% if category_jobs %}
        <h3 class="widget-title">More jobs in <a href="{% url 'jobs:job_list_category' slug=object.category.slug %}">{{ object.category.name }}</a></h3>

        <ul class="menu">
            {% if object.company %}
                {% for job in category_jobs %}
                <li><a href="{% url 'jobs:job_list_company' slug=object.company.slug %}">{{ job.display_location }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
        {% endif %}
    </div>
{% endblock right_sidebar_header %}

{% block extra_js %}
{% if jobs_board_admin %}
<script type="text/javascript">
    // TODO: allow configuring canned responses in admin
    var responses = {
      "voluntary": "The Python Job Board is for paid positions only. The Python Community has a separate Wiki for listing voluntary positions available at https://wiki.python.org/moin/VolunteerOpportunities.",
      "not_python": "The Python Job Board is for positions in which the primary role involves the Python programming language or development frameworks based on Python.\n\nPlease rephrase and resubmit.\n\nThanks.",
      "formatting": "Please resubmit your posting and check that the job description and/or requirements text renders fine in the job preview.\n\nThanks.",
      "duplicate": "This seems to be a duplicate of your earlier posting.\n\nIf not, please rephrase to make the difference clear.\n\nThanks."
    };
    $(document).ready(function() {
        var comment_field = $('#id_comment');
        $('#canned_response').change(function(){
            comment_field.val(responses[$(this).val()]);
        });
    });
</script>
{% endif %}
{% endblock %}

templates/jobs/job_types.html
{% extends "jobs/base.html" %}
{% load boxes %}

{% block page_title %}Our Job Types | {{ SITE_INFO.site_name }}{% endblock %}
{% block content_attributes %}with-right-sidebar{% endblock %}

{% block header_message %}Jobs by Technology!{% endblock %}
{% block header_action %}{{ jobs_count }} Python jobs in {{ types|length }} different types.{% endblock %}

{% block content %}
<div class="row">

    <ol class="list-recent-jobs list-row-container menu">
        {% for type in types %}
            <li><a href="{% url 'jobs:job_list_type' slug=type.slug %}">{{ type.name }}</a></li>
        {% endfor %}
    </ol>

</div>
{% endblock content %}